version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  # nats:
  #   image: nats:2
  #   ports:
  #     - "4222:4222"
  #     - "8222:8222"

  # localstack:
  #   image: localstack/localstack
  #   environment:
  #     - SERVICES=sqs
  #   ports:
  #     - "4566:4566"
  kafka:
    image: bitnami/kafka:3.7 # fixe a tag que você quer
    container_name: kafka
    ports:
      - "9092:9092" # broker
      - "9093:9093" # controller (intra-cluster)
    environment:
      # ---- KRaft ----
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # ---- listeners ----
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes # só para dev/PoC

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command: >
      redpanda start
      --smp 1
      --memory 512M
      --overprovisioned
      --node-id 0
      --check=false
    ports:
      - "9094:9092" # Kafka API
      - "9644:9644" # Admin API (Prometheus)
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  # nodered:
  #   image: nodered/node-red:latest
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - nodered_data:/data

  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]   # porta interna do redpanda
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        connect:
          enabled: true
          clusters:
            - name: datagen
              url: http://connect:8083
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  nodered_data:
  redpanda_data:
