input:
  label: rabbit_source
  amqp_0_9:
    url: amqp://rabbitmq:5672/
    queue: test            # mesma fila do script
    prefetch_count: 500
    tls:
      enabled: false

pipeline:
  processors:
    # Exemplo: garante que cada mensagem tenha iso-timestamp p/ BigQuery
    - mapping: |
        root = this
        root.ingested_at = now()

output:
  label: fanout
  broker:
    pattern: fan_out
    outputs:
      # 1) publica no Redpanda (para outras apps/observabilidade)
      - kafka:
          addresses: [ redpanda:9092 ]
          topic: test
          batching:
            count: 1
      # 2) envia direto p/ BigQuery
      - gcp_bigquery:
          project: meu-projeto
          dataset: poc
          table: events
          credentials_json: ${FILE:/secrets/gcp-creds.json}
          format: NEWLINE_DELIMITED_JSON
